server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: face-detection-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Face Detection API
    description: OpenCV-based face detection service for CV/internship applications
    version: 1.0.0
    contact:
      name: Nguyen Tuan Khanh
      email: your.email@example.com

# Custom application properties
app:
  name: Face Detection API
  version: 1.0.0
  description: "Professional face detection service using Spring Boot and OpenCV"
  python:
    script-path: ../python-scripts/enhanced_face_detector.py
    timeout: 30000 # 30 seconds
  temp:
    directory: ./temp           
  max:
    file:
      size: 10485760

# Logging configuration
logging:
  level:
    com.facedetect: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/face-detection-api.log
